#!/usr/bin/env python3

import sys

from luxafor_auto import core

command = sys.argv[1]

if command == "start":
    try:
        core.run()
    except KeyboardInterrupt:
        core.kill()
        sys.exit("\nCanceling.")
elif command == "stop":
    core.kill()
    sys.exit("\nStopping normally")
